project:
  type: website

website:
  title: "Jean's Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: resume.qmd
        text: Resume

format:
  html:
    theme:
      - quartz
    toc: true

execute:
  freeze: auto

